/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
export declare const IMediaPlayerSourceObserver: t.TIface;
declare const exportedTypeSuite: t.ITypeSuite;
export default exportedTypeSuite;
//# sourceMappingURL=ICmviotMediaPlayerSource-ti.d.ts.map